kind: pipeline
name: default

steps:
- name: build
  image: alpine:3.10
  environment:
    RELEASE: "0.01"
    GHR_VERSION: "0.12.1"
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
  - mkdir -p package/bin
  - cp build_index package/bin
  - apk add ca-certificates go git build-base clang
  - clang --static -Os uchroot.c -o uchroot
  - cp uchroot package/bin
  - CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' espbuild.go tar.go git.go
  - cp espbuild package/bin
  - tar cfj espbuild-static.tar.bz2 -C package .
  - go mod init .
  - go get github.com/tcnksm/ghr@v$GHR_VERSION
  - ~/go/bin/ghr -u $DRONE_REPO_OWNER -r $DRONE_REPO_NAME -c $DRONE_COMMIT_SHA -delete $RELEASE espbuild-static.tar.bz2

trigger:
  event:
  - push
