version: 2.1

executors:
  alpine:
    docker:
      - image: alpine:3.9
    working_directory: ~/
    environment:
      VERSION: 0.01
      GHR_VERSION: 0.12.1

jobs:
  espbuild:
    executor: alpine
    steps:
      - run: apk add ca-certificates libarchive-tools go git clang build-base
      - checkout
      - run:
          name: Build
          command: |
            clang --static -Os super_chroot.c -o super_chroot
            strip super_chroot
            go get go.starlark.net/starlark
            CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' espbuild.go
            mkdir -p ~/build/bin
            cp ~/espbuild ~/build/bin
            cp ~/build_index ~/build/bin
            cp ~/super_chroot ~/build/bin
            bsdtar cvfz ~/espbuild-static.tar.gz -C ~/build .
            go mod init .
            go get github.com/tcnksm/ghr@v${GHR_VERSION}
            ~/go/bin/ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/espbuild-static.tar.gz

workflows:
  build:
    jobs:
      - espbuild
