version: 2.1

executors:
  alpine:
    docker:
      - image: alpine:3.9
    working_directory: ~/
    environment:
      VERSION: 0.01

jobs:
  build_espbuild:
    executor: alpine
    steps:
      - run: apk add ca-certificates go git build-base
      - checkout
      - run: pwd
      - run: ls -al
      - run: go get go.starlark.net/starlark
      - run: CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' .
      - run: go mod init .
      - run: go get github.com/tcnksm/ghr@v0.12.1
      - run: ~/go/bin/ghr $GHR_FLAGS -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} ~/espbuild

workflows:
  build:
    jobs:
      - build_espbuild
